config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :calendars do
    collection do
      get :view_all
      get :view_all_in_one
    end
  end
  namespace :admin do
    resources :users
  end
  devise_for :users, path: 'users'
  # devise_for :admin_users, path: 'admins', controllers: { sessions: "admin_users/sessions", registrations: "admin_users/registrations" }
  devise_for :admin_users, skip: [:sessions]
  as :admin_user do
    get 'admin', to: 'admin_users/sessions#new', as: :new_admin_user_session
    post 'admin', to: 'admin_users/sessions#create', as: :admin_user_session
    delete 'sign_out', to: 'admin_users/sessions#destroy', as: :destroy_admin_user_session, via: Devise.mappings[:admin_user].sign_out_via
  end
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get 'welcome/index'
  root 'welcome#index'
  get 'admin/dashboard'
 
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  has_many :events
  has_many :calendar_users
  has_many :users, through: :calendar_users

  validates_presence_of :title

  after_create :update_events

  def all_users
    user_ids = ([user.id] + users.ids).uniq
    User.where(id: user_ids)
  end

  def country_name
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name if country
  end

  def update_events
    # capi = Calendarific::V2.new(ENV['CALENDARIFIC_API_KEY'])
    # parameters = {'country' => country_code, 'year' => Date.today.year}
    # data = capi.holidays(parameters)
    # holidays = data["response"]["holidays"] rescue nil

    if self.country_code.present?
      begin
        (0..12).each do |i|
          # uri = URI.parse("https://calendarific.com/api/v2/holidays?&api_key=#{ENV['CALENDARIFIC_API_KEY']}&country=#{self.country_code}&year=#{Date.today.year + i}")
          # http = Net::HTTP.new(uri.host, uri.port)
          # http.use_ssl = true
          # request = Net::HTTP::Get.new(uri.request_uri)
          # response = http.request(request)
          # data = ActiveSupport::JSON.decode(response.body)
          # holidays = data["response"]["holidays"] rescue nil

          # if holidays.present?
          #   holidays.each do |holiday|
          #     self.events.create(title: holiday["name"], description: holiday[:description], start: holiday["date"]["iso"].to_date.beginning_of_day, end: holiday["date"]["iso"].to_date.end_of_day)
          #   end
          # end

          uri = URI.parse("https://date.nager.at/api/v2/PublicHolidays/#{Date.today.year + i}/#{self.country_code}")
          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = true
          request = Net::HTTP::Get.new(uri.request_uri)
          response = http.request(request)
          data = ActiveSupport::JSON.decode(response.body)
          # holidays = data["response"]["holidays"] rescue nil

          if data.present?
            data.each do |holiday|
              self.events.create(title: holiday["name"], description: holiday["localName"], start: holiday["date"].to_date.beginning_of_day, end: holiday["date"].to_date.end_of_day)
            end
          end

        end
      rescue
      end
    end
    
  end

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = current_user.all_calendars
  end

  def view_all
    @calendars = current_user.all_calendars
  end

  def view_all_in_one
    # @calendars = current_user.all_calendars

    month = Date.today.month > 6 ? 6 : 0
    @start_date = params[:start_date].present? ? params[:start_date].to_date : Date.today.beginning_of_year + month.months
    @prev_date = @start_date - 6.months
    @next_date = @start_date + 6.months
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
    month = Date.today.month > 6 ? 6 : 0
    @start_date = params[:start_date].present? ? params[:start_date].to_date : Date.today.beginning_of_year + month.months
    @prev_date = @start_date - 6.months
    @next_date = @start_date + 6.months
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new(user_id: current_user.id)
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.user_id = current_user.id
    respond_to do |format|
      if @calendar.save

        emails = JSON.parse params[:calendar][:users] rescue []
        emails.each do |email|
          user = User.find_by_email(email)
          user = User.invite!(email: email) if user.nil?
          calendar_user = @calendar.calendar_users.create(user_id: user.id)
        end

        # User.where(id: params[:calendar][:users]).each do |user|
        #   calendar_user = @calendar.calendar_users.create(user_id: user.id)
        #   CalendarMailer.send_join_email(calendar_user).deliver_later
        # end

        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        if @calendar.user == current_user

          emails = JSON.parse params[:calendar][:users] rescue []
          user_ids = User.where(email: emails)
          @calendar.calendar_users.where.not(user_id: user_ids).destroy_all
          emails.each do |email|
            user = User.find_by_email(email)
            user = User.invite!(email: email) if user.nil?
            calendar_user = @calendar.calendar_users.find_or_create_by(user_id: user.id)
          end

          # @calendar.calendar_users.where.not(user_id: user_ids).destroy_all
          # User.where(id: user_ids).each do |user|
          #   if @calendar.calendar_users.where(user_id: user.id).first.nil?
          #     calendar_user = @calendar.calendar_users.create(user_id: user.id)
          #     CalendarMailer.send_join_email(calendar_user).deliver_later
          #   end
          # end

        end
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:title, :country_code, :color, :discription)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_calendar.html.erb
<div class="text-center"><h5><%= date.strftime("%B") %></h5></div>
<div id="calendar_<%= index %>"></div>

<script type="text/javascript">

  $('#calendar_<%= index %>').fullCalendar({
    defaultDate: new Date(<%= date.year %>, <%= date.month - 1 %>, <%= date.day %>),
    // header: {
    //   left: 'prev,next today',
    //   center: 'title',
    //   right: 'month,agendaWeek,agendaDay'
    // },
    defaultView: 'agendaMonth',
    displayEventTime: false,
    header: false,
    selectable: true,
    selectHelper: true,
    // editable: true,
    eventLimit: true,
    events: "/events.json?calendar_id=<%= calendar.id %>",

    views: {
      // listThreeDay: {
      //   type: 'list',
      //   duration: {
      //     days: 31
      //   }
      // },
      agendaMonth: {
        type: 'agendaDay',
        maxTime: "<%= (date.beginning_of_month..date.end_of_month).count %>.00:00:00",
        slotDuration: '24:00:00',
        slotLabelFormat: [
          'WW dd D' // lower level of text
        ],
        buttonText: 'custom agenda'
      },
    },

    select: function(start, end) {
      $.getScript("/events/new?start_date=" + start + "&end_date=" + end + "&main_calendar_id=<%= calendar.id %>&start=<%= start_date %>", function() {
        $('.start_hidden').val(moment(start).format('YYYY-MM-DD HH:mm'));
        $('.end_hidden').val(moment(end).format('YYYY-MM-DD HH:mm'));
      });
      $('#calendar').fullCalendar('unselect');
    },
    // eventDrop: function(event, delta, revertFunc) {
    //   event_data = { 
    //     event: {
    //       id: event.id,
    //       start: event.start.format(),
    //       end: event.end.format()
    //     }
    //   };
    //   $.ajax({
    //     url: event.update_url + "&start_date=<%= start_date %>",
    //     data: event_data,
    //     type: 'PATCH'
    //   });
    // },
    eventClick: function(event, jsEvent, view) {
      $.getScript(event.edit_url + "?start=<%= start_date %>", function() {
        $('.start_hidden').val(moment(event.start).format('YYYY-MM-DD HH:mm'));
        $('.end_hidden').val(moment(event.end).format('YYYY-MM-DD HH:mm'));
      });
    },
    eventMouseover: function(event, jsEvent, view) {
      $(this).attr("title", event.title);
      // $(this).tooltip();
    }
  });
</script>

app/views/calendars/_calendar_all_in_one.html.erb
<div class="text-center"><h5><%= date.strftime("%B") %></h5></div>
<div id="calendar_<%= index %>"></div>

<script type="text/javascript">

  $('#calendar_<%= index %>').fullCalendar({
    defaultDate: new Date(<%= date.year %>, <%= date.month - 1 %>, <%= date.day %>),
   
    defaultView: 'agendaMonth',
    displayEventTime: false,
    header: false,
    selectable: true,
    selectHelper: true,
    eventLimit: true,
    events: "/events.json",

    views: {
      
      agendaMonth: {
        type: 'agendaDay',
        maxTime: "<%= (date.beginning_of_month..date.end_of_month).count %>.00:00:00",
        slotDuration: '24:00:00',
        slotLabelFormat: [
          'WW dd D' // lower level of text
        ],
        buttonText: 'custom agenda'
      },
    },

    
    eventMouseover: function(event, jsEvent, view) {
      $(this).attr("title", event.title);
    }
  });
</script>

app/views/calendars/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: calendar, local: true) do |form| %>
      <% if calendar.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

          <ul>
          <% calendar.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row">
        <%= form.label :title, class: "control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= form.text_field :title, class: "form-control" %>
        </div>
      </div>

      <!-- <div class="form-group row">
        <%= form.label :no_country, class: "control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= check_box_tag :no_country, 1, @calendar.country_code.blank? %>
        </div>
      </div> -->

      <div class="form-group row">
        <%= form.label :country_code, "Country", class: "control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= form.country_select :country_code, {prompt: "Select Country (Blank)"}, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :color, class: "control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= form.text_field :color, class: "form-control" %>
        </div>
      </div>

      <% if @calendar.user == current_user %>
        <div class="form-group row">
          <%= form.label :users, class: "control-label col-sm-2" %>
          <div class="col-sm-10">
            <%#= form.select :users, User.all.map{|u| [u.email, u.id]}, {selected: @calendar.users.ids}, class: "form-control", multiple: true %>
            <%= form.text_field :users, value: "#{@calendar.users.map(&:email).sort}", class: "form-control" %>
          </div>
        </div>
      <% end %>

      <div class="form-group row">
        <%= form.label :discription, "Description", class: "control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= form.text_area :discription, class: "form-control", rows: 3 %>
        </div>
      </div>

      <br>
      <div class="actions">
        <%= form.submit :class => "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

<style type="text/css">
  .minicolors-theme-default.minicolors{display:block;}
  .minicolors-theme-default .minicolors-input{height:auto; width:100%;}
</style>

<script type="text/javascript">
  $('#calendar_color').minicolors();
  // $( "#calendar_users" ).select2({
  //   theme: "bootstrap4"
  // });
  $('#calendar_users').multiple_emails();

  

  // $(document).on('change', '#no_country', function() {
  //   if(this.checked) {
  //     $("#country_dropdown").hide();
  //     $("#calendar_country_code").val("");
  //   }
  //   else{
  //     $("#country_dropdown").show();
  //   }
  // });


</script>

app/views/calendars/edit.html.erb
<div class="row">
  <div class="col-md-12">
  	 <div class="page-body">
      <h1 class="border-bottom mb-5">
        <span>Edit Calendar</span>
        <span class="float-right">
          <%= link_to 'Show', @calendar, class: "btn btn-success" %> 
          <%= link_to 'Back', calendars_path, class: "btn btn-primary" %>
        </span>
      </h1>
			<%= render 'form', calendar: @calendar %>
		</div>
	</div>
</div>

app/views/calendars/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-body">
      <h1 class="border-bottom mb-5">
        <span>Calendars (<%= @calendars.count %>)</span>
        <span class="float-right">
          <%= link_to 'New Calendar', new_calendar_path, class: "btn btn-primary" %>
        </span>
      </h1>
      <% if @calendars.any? %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Title</th>
              <th>Country</th>
              <th>Color</th>
              <th>Owner</th>
              <th>Users</th>
              <th>Description</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @calendars.each do |calendar| %>
              <tr>
                <td><%= link_to calendar.title, calendar %></td>
                <td><%= calendar.country_name %></td>
                <td><span class="badge text-white" style="background-color:<%= calendar.color %>"><%= calendar.color %></span></td>
                <td><%= calendar.user.email %></td>
                <td>
                  <% calendar.users.map(&:email).sort.each do |email| %>
                    <%= email %><br>
                  <% end %>
                </td>
                <td><%= calendar.discription %></td>
                <td>
                  <%= link_to 'View', calendar %> | 
                  <%= link_to 'Edit', edit_calendar_path(calendar) %> | 
                  <%= link_to 'Delete', calendar, method: :delete, data: {confirm: 'Are you sure?'} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>You don't have any calendar created yet. Please create <%= link_to 'here', new_calendar_path %>.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/calendars/new.html.erb
<div class="row">
  <div class="col-md-12">
  	 <div class="page-body">
      <h1 class="border-bottom mb-5">
        <span>New Calendar</span>
        <span class="float-right">
          <%= link_to 'Back', calendars_path, class: "btn btn-primary" %>
        </span>
      </h1>
			<%= render 'form', calendar: @calendar %>
		</div>
	</div>
</div>

app/views/calendars/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-body">
		  <h1 class="border-bottom mb-4">
		  	<div class="row">
			    <div class="badge text-white col-md-4" style="background-color:<%= @calendar.color %>"><%= @calendar.title %></div>
			    <div class="col-md-4 text-center">
			    	<div>
			    		<a href="<%= calendar_path(@calendar, start_date: @prev_date) %>" class="btn btn-lg">
			    			<span class="fc-icon fc-icon-left-single-arrow"></span>
			    		</a>
			    		<a href="<%= calendar_path(@calendar, start_date: @next_date) %>" class="btn btn-lg">
			    			<span class="fc-icon fc-icon-right-single-arrow"></span>
			    		</a>
			    		<a href="javascript:void(0);" class="btn">
			    			<h3><%= @start_date.year %></h3>
			    		</a>
			    	</div>
			    </div>
			    <div class="text-right col-md-4">
			      <%= link_to 'Edit', edit_calendar_path(@calendar), class: "btn btn-success" %>
			      <%= link_to 'Back', calendars_path, class: "btn btn-primary" %>
			    </div>
		    </div>
		  </h1>
		  <div class="row">
		  	<div class="col-md-9">
		  		<%= @calendar.discription %>
	  		</div>
		  </div>
		  <div class="row">
		  	<% date = @start_date %>
		  	<% (1..6).each do |i| %>
		  	 	<div class="col-md-2 calendar-box <% if date.strftime('%B%Y') == Date.today.strftime('%B%Y') %>todays_month<% end %>" id="calendar_box_<%= @calendar.id %>" style="margin-bottom:50px;">
			  		<%= render "calendar", calendar: @calendar, index: i, date: date, start_date: @start_date %>
		  		</div>
		  		<% date = date.next_month %>
	  		<% end %>
	  	</div>
		</div>
  </div>
</div>

<div id='remote_container'></div>

app/views/calendars/view_all.html.erb
<div class="row">
	<% if @calendars.any? %>
	  <% @calendars.each do |calendar| %>
	    <div class="col-md-6 calendar_box" id="calendar_box_<%= calendar.id %>">
	      <%= render "calendar", calendar: calendar %>
	    </div>
	  <% end %>
  <% else %>
    <p>You don't have any calendar created yet. Please create <%= link_to 'here', new_calendar_path %>.</p>
  <% end %>
</div>

<div id='remote_container'></div>

app/views/calendars/view_all_in_one.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-body">
		  <h1 class="border-bottom mb-4">
		  	<div class="row">
			    <div class="col-md-12 text-center">
			    	<div>
			    		<a href="<%= view_all_in_one_calendars_path(start_date: @prev_date) %>" class="btn btn-lg">
			    			<span class="fc-icon fc-icon-left-single-arrow"></span>
			    		</a>
			    		<a href="<%= view_all_in_one_calendars_path(start_date: @next_date) %>" class="btn btn-lg">
			    			<span class="fc-icon fc-icon-right-single-arrow"></span>
			    		</a>
			    		<a href="javascript:void(0);" class="btn">
			    			<h3><%= @start_date.year %></h3>
			    		</a>
			    	</div>
			    </div>
		    </div>
		  </h1>
		  <div class="row">
		  	<% date = @start_date %>
		  	<% (1..6).each do |i| %>
		  	 	<div class="col-md-2 calendar-box <% if date.strftime('%B%Y') == Date.today.strftime('%B%Y') %>todays_month<% end %>" style="margin-bottom:50px;">
			  		<%= render "calendar_all_in_one", index: i, date: date, start_date: @start_date %>
		  		</div>
		  		<% date = date.next_month %>
	  		<% end %>
	  	</div>
		</div>
  </div>
</div>
<div id='remote_container'></div>