config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :calendars do
    collection do
      get :view_all
      get :view_all_in_one
    end
  end
  namespace :admin do
    resources :users
  end
  devise_for :users, path: 'users'
  # devise_for :admin_users, path: 'admins', controllers: { sessions: "admin_users/sessions", registrations: "admin_users/registrations" }
  devise_for :admin_users, skip: [:sessions]
  as :admin_user do
    get 'admin', to: 'admin_users/sessions#new', as: :new_admin_user_session
    post 'admin', to: 'admin_users/sessions#create', as: :admin_user_session
    delete 'sign_out', to: 'admin_users/sessions#destroy', as: :destroy_admin_user_session, via: Devise.mappings[:admin_user].sign_out_via
  end
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get 'welcome/index'
  root 'welcome#index'
  get 'admin/dashboard'
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 	devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

 	has_many :calendars

 	has_many :calendar_users

 	def all_calendars
 		calendar_ids = (calendars.ids + calendar_users.map(&:calendar_id)).uniq
 		Calendar.where(id: calendar_ids)
 	end
 	
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: user }
      else
        format.html { render :new }
        format.json { render json: user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: user }
      else
        format.html { render :edit }
        format.json { render json: user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<div class='container-fluid login bg-dark-grey'>
  <div class="container">
    <div class="row mt50b150">
      <div class="col-md-3"></div>
        <div class="col-md-6">
          <%= form_for([:admin, @user]) do |form| %>
            <div class="form-group"">
              <%= form.label :email %>
              <%= form.text_field :email, class: "form-control" %>
            </div>

            <div class="field">
              <%= form.label :password %>
              <%= form.password_field :password, class: "form-control" %>
            </div>

            <div class="field">
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation, class: "form-control" %>
            </div>
            <br>
            <div class="actions">
              <%= form.submit :class => "btn btn-primary"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/users/edit.html.erb
<br><br><br><br><br><br>
<center><h1>Editing User</h1></center>

<%= render 'form', admin_user: @admin_user %>

<div class="col-md-3" style="float: right">
<%= link_to 'Show', admin_user_path, class: "btn btn-success"%>
<%= link_to 'Back', admin_users_path, class: "btn btn-primary"  %>
</div><br>

app/views/admin/users/index.html.erb
<br><br><br>
<div class="col-md-3">
<%= link_to 'Add New User', new_admin_user_path,class: "btn btn-primary" %></div>
<div class="container">
  <center><h1>Users</h1></center>
  <table class="table table-hover">
    <thead>
       <tr>
      <th>Email</th>
      <th>Verified?</th>
      <!-- <th>Password confirmation</th> -->
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.confirmed? ? "Yes" : "No" %></td>
        <!-- <td><%#= user.password_confirmation %>********</td> -->
        <td><%= link_to 'Show', [:admin, user] ,class: "btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user),class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger"%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div><br><br><br><br>

app/views/admin/users/new.html.erb
<br><br><br><br><br><br>
<center><h1>New User</h1></center>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<br><br><br><br><br><br>
<div class="col-md-3" style="float: right">
<%= link_to 'Edit', edit_admin_user_path(@user),class: "btn btn-success " %>
<%= link_to 'Back', admin_users_path, class: "btn btn-primary"  %>
</div><br>
<div class="container">
	<table class="table">
	<p>
	  <strong>Email:</strong>
	  <%= @user.email %>
	</p>

	<p>
	  <strong>Password:</strong>
	  <%#= @user.password %>
	  ********
	</p>

	<p>
	  <strong>Password confirmation:</strong>
	  <%#= @user.password_confirmation %>
	  ********
	</p>
	</table>
</div>