config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :calendars do
    collection do
      get :view_all
      get :view_all_in_one
    end
  end
  namespace :admin do
    resources :users
  end
  devise_for :users, path: 'users'
  # devise_for :admin_users, path: 'admins', controllers: { sessions: "admin_users/sessions", registrations: "admin_users/registrations" }
  devise_for :admin_users, skip: [:sessions]
  as :admin_user do
    get 'admin', to: 'admin_users/sessions#new', as: :new_admin_user_session
    post 'admin', to: 'admin_users/sessions#create', as: :admin_user_session
    delete 'sign_out', to: 'admin_users/sessions#destroy', as: :destroy_admin_user_session, via: Devise.mappings[:admin_user].sign_out_via
  end
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get 'welcome/index'
  root 'welcome#index'
  get 'admin/dashboard'
 
end

app/views/layouts/_dashboard.html.erb
<div class="fixed-top">
  <header class="topbar">
      <div class="container">
        <div class="row">
          <!-- social icon-->
          <div class="col-sm-12">
            <ul class="social-network">
							<p class="navbar-text pull-right">
							  <% if admin_user_signed_in? %>
							    Logged in as <strong>Admin</strong>&nbsp;&nbsp;&nbsp;
				            <a>
							    <%#= link_to 'Edit profile', edit_admin_user_registration_path, :class => 'navbar-link' %></a> 
				            <a >
							    <%= link_to "Logout", destroy_admin_user_session_path, method: :delete, :class => 'navbar-link'  %></a>
							  <% else %>
							    <%#= link_to "Sign up", new_admin_user_registration_path, :class => 'navbar-link'  %>
							    <%= link_to "Login", new_admin_user_session_path, :class => 'navbar-link'  %>
							  <% end %>
							</p>
        		</ul>
          </div>
        </div>
      </div>
  </header>
  <% if admin_user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
    <div class="container">
      <a class="navbar-brand" href="<%= admin_dashboard_path %>" style="text-transform: uppercase;"> User Cms</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link pull-right" href="<%= admin_users_path %>" style="margin-right: 424px;">Users
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
 <%end%>
</div>
<div class="footer">
  <p>@copyright2019</p>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'download.png'%>
  </head>
  <body>
 		<%= render 'layouts/dashboard' %>
		<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>" style="z-index:9999;">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong><%= key %>!</strong> <%= value %>
      </div>
		<% end %>
   	<%= yield %>
  </body>
</html>
<style type="text/css">
	body {
    margin: 0;
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    background-color: #f7f7f7;
}
.navbar {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -ms-flex-align: center;
    align-items: center;
    -ms-flex-pack: justify;
    justify-content: space-between;
    padding: 5px;
}

/*
headeer top
*/
.topbar{
  background-color: #212529;
  padding: 0;
}

.topbar .container .row {
  margin:-7px;
  padding:0;
}

.topbar .container .row .col-md-12 { 
  padding:0;
}

.topbar p{
  margin:0;
  display:inline-block;
  font-size: 13px;
  color: #f1f6ff;
}

.topbar p > i{
  margin-right:5px;
}
.topbar p:last-child{
  text-align:right;
} 

header .navbar {
    margin-bottom: 0;
}

.topbar li.topbar {
    display: inline;
    padding-right: 18px;
    line-height: 52px;
    transition: all .3s linear;
}

.topbar li.topbar:hover {
    color: #1bbde8;
}

.topbar ul.info i {
    color: #131313;
    font-style: normal;
    margin-right: 8px;
    display: inline-block;
    position: relative;
    top: 4px;
}

.topbar ul.info li {
    float: right;
    padding-left: 30px;
    color: #ffffff;
    font-size: 13px;
    line-height: 44px;
}

.topbar ul.info i span {
    color: #aaa;
    font-size: 13px;
    font-weight: 400;
    line-height: 50px;
    padding-left: 18px;
}

ul.social-network {
  border:none;
  margin:0;
  padding:0;
}

ul.social-network li {
  border:none;  
  margin:0;
}

ul.social-network li i {
  margin:0;
}

ul.social-network li {
    display:inline;
    margin: 0 5px;
    border: 0px solid #2D2D2D;
    padding: 5px 0 0;
    width: 32px;
    display: inline-block;
    text-align: center;
    height: 32px;
    vertical-align: baseline;
    color: white !important;
}

ul.social-network {
  list-style: none;
  margin: 5px 0 10px -25px;
  float: right;
}

.waves-effect {
    position: relative;
    cursor: pointer;
    display: inline-block;
    overflow: hidden;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
    vertical-align: middle;
    z-index: 1;
    will-change: opacity, transform;
    transition: .3s ease-out;
    color: #fff;
}
a {
  color: white;
  text-decoration: none;
}

li {
    list-style-type: none;
}
.bg-image-full {
    background-position: center center;
    background-repeat: no-repeat;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;
}
.bg-dark {
    background-color: #222!important;
}

.mx-background-top-linear {
    background: -webkit-linear-gradient(45deg, #00ce81 48%, #1b1e21 48%);
    background: -webkit-linear-gradient(left, #00ce81 48%, #1b1e21 48%);
    background: linear-gradient(45deg, #00ce81 48%, #1b1e21 48%);
}
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #00ce81;
   color: black;
}
.footer p{
	margin-top: 16px;
	text-align: center;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllYear.Ninja Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://kit.fontawesome.com/5666044c33.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'download.png'%>

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-5743268646467547",
        enable_page_level_ads: true
      });
    </script>

  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
      <a class="navbar-brand" href="/">Home</a>

      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "All Calendars", view_all_in_one_calendars_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Manage Calendars", calendars_path, class: 'nav-link' %>
          </li>
        </ul>
      <% end %>

      <ul class="navbar-nav" style="position: absolute;right: 30px;">
        <% if user_signed_in? %>
          <li class="nav-item"><a class="nav-link">Logged in as <strong><%= current_user.email %></strong>.</a></li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
          </li>
        <%end%>
      </ul>
    </nav>

    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong><%= key %>!</strong> <%= value %>
      </div>
    <% end %>

    <% if params[:controller] == "welcome" && params[:action] == "index" %>
      <%= yield %>
    <% else %>
      <div class="container container-fluid">
        <%= yield %>
      </div>
    <% end %>

  </body>
</html>

<script type="text/javascript">
  $(document).ready(function() {
    $(".fc-slats .fc-time span").lettering();
    // $('span.char5:contains("u")').closest('tr').css('background-color', 'grey');
    // $('span.char4:contains("T")').closest('tr').css('background-color', 'white');
    $('span.char4:contains("S")').closest('tr').css('background-color', 'lightgray');

    var count = 0;
    var temp_week_number = ""

    $("tr[data-time]").each(function( index ) {
      week_number_1 = $(this).find(".char1").text();
      week_number_2 = $(this).find(".char2").text();
      if (week_number_1 == "0"){
        week_number_1 = "";
      }
      week_number = week_number_1 + week_number_2;

      if (temp_week_number != week_number){
        // $(this).append("<td class='td_week_number'>" + week_number + "</td>")
        $(this).find(".fc-widget-content:last").html(week_number);
        $(this).find(".fc-widget-content:last").addClass("td_week_number");
      }
      else{
        // $(this).append("<td class='td_week_number td_week_number_blank'>" + " " + "</td>")
      }
      temp_week_number = week_number
      $(this).find(".char1").remove()
      $(this).find(".char2").remove()
      $(this).find(".char3").remove()
      $(this).find(".char5").remove()
      

      day = $(this).find(".char7").text() + $(this).find(".char8").text();
      todays_date = <%= Date.today.day %>;
      if (day == todays_date){
        $(this).addClass("todays_date");
      }



    });


  });
</script>